include_configs:
  - data_abc_test.yaml

train_dataset: Points2SurfDataset
train_val_num_workers: 4
train_kwargs:
  base_path: "../data/points2surf"
  dataset_name: "train"
  type_name: "var-n"
  transforms: []
  split: "train"
  random_seed: 0

val_dataset: Points2SurfDataset
val_kwargs:
  base_path: "../data/points2surf"
  dataset_name: "train"
  type_name: "var-n"
  transforms: []
  split: "val"
  random_seed: "fixed"
